Attempts to account for path differences between RHEL and Ubuntu

diff --git a/give b/give
--- a/give
+++ b/give
@@ -60,8 +60,8 @@ function get_uids() {
         error "get_uids expects one (and only one) argument (target user)"
     fi
     their_uname="${1:-INVALID_USER_NAME}"
-    my_uid="$(/bin/id -u)" || error "could not get id for current user"
-    their_uid="$(/bin/id -u "$their_uname")" || error "could not get id for target user ($1)"
+    my_uid="$(env id -u)" || error "could not get id for current user"
+    their_uid="$(env id -u "$their_uname")" || error "could not get id for target user ($1)"
 }
 
 does_gift_store_exist() {
@@ -101,7 +101,7 @@ function _give() {
     fi
 
     validate "$@"
-    /usr/bin/cp --target-directory="$target_dir" -- "$@"
+    env cp --target-directory="$target_dir" -- "$@"
 }
 
 function _ungive() {
@@ -116,8 +116,8 @@ function _ungive() {
     their_uname="$1"
     shift
 
-    my_uid="$(/bin/id -u)"
-    their_uid="$(/bin/id -u "$their_uname")"
+    my_uid="$(env id -u)"
+    their_uid="$(env id -u "$their_uname")"
 
     target_dir="$gift_store/$my_uid-$their_uid"
     if [[ ! -d "$target_dir" ]]; then
@@ -126,7 +126,7 @@ function _ungive() {
 
     while [[ -n "$1" ]]; do
         validate "$1"
-        /usr/bin/rm -- "$target_dir/$1" || error "could not delete file from temporary gift storage!"
+        env rm -- "$target_dir/$1" || error "could not delete file from temporary gift storage!"
     done      
 }
 
@@ -139,8 +139,8 @@ function _take() {
     their_uname="$1"
     shift
 
-    my_uid="$(/bin/id -u)"
-    their_uid="$(/bin/id -u "$their_uname")"
+    my_uid="$(env id -u)"
+    their_uid="$(env id -u "$their_uname")"
 
 
     target_dir="$gift_store/$their_uid-$my_uid"
@@ -150,7 +150,7 @@ function _take() {
     fi
 
     cwd="$(pwd)"
-    (cd "$target_dir" && /usr/bin/cp --target-directory="$cwd" "$@" && /usr/bin/rm "$@" )
+    (cd "$target_dir" && env cp --target-directory="$cwd" "$@" && env rm "$@" )
 }
 
 
